# Generated by Django 3.1 on 2020-09-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/None/<django.db.models.fields.CharField>/'),
        ),
    ]
