# Generated by Django 3.1 on 2020-09-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200903_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
